name: Automation_Snowflake_Project_AirflowScheduled
description: test random description
version: 2.0.0
author: abhisheks+e2etests@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/SQL_Composer_AirflowScheduled_Snowflake:
    name: SQL_Composer_AirflowScheduled_Snowflake
    description: Job DBT
    fabricUID: 18
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: '*/5 5-6 8 4 *'
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2025-04-08 05:31:34'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects:
    - '11387'
  jobs/SQL_MWAA_AirflowScheduled_Snowflake:
    name: SQL_MWAA_AirflowScheduled_Snowflake
    description: Job DBT
    fabricUID: 20
    scheduler:
      MWAA: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: '*/5 5-6 8 4 *'
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2025-04-08 05:32:35'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects:
    - '11387'
  jobs/SQL_PMAir_AirflowScheduled_Snowflake:
    name: SQL_PMAir_AirflowScheduled_Snowflake
    description: Job DBT
    fabricUID: 16
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: '*/5 5-6 8 4 *'
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2025-04-08 05:33:48'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects:
    - '11387'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-04-08 05:28:50'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/testModelSchdRun_Automation_Snowflake_Project_AirflowScheduled:
    name: testModelSchdRun_Automation_Snowflake_Project_AirflowScheduled
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: C_INT64
        dataType:
          type: Number
      - name: C_BIGNUMERIC
        dataType:
          type: Number
      - name: C_STRING
        dataType:
          type: String
      - name: C_FLOAT64
        dataType:
          type: Float
      - name: C_BOOL
        dataType:
          type: String
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/testmodel/testModelSchdRun_Automation_Snowflake_Project_AirflowScheduled.sql
    - .prophecy/ide/models/testModelSchdRun_Automation_Snowflake_Project_AirflowScheduled.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2025-04-08 05:30:50'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2025-04-08 05:28:52'
sqlSeeds:
  .prophecy/metadata/sqlseeds/testSeedSchdRun_Automation_Snowflake_Project_AirflowScheduled:
    name: testSeedSchdRun_Automation_Snowflake_Project_AirflowScheduled
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: c_int64
        dataType:
          type: Number
      - name: c_bignumeric
        dataType:
          type: Number
      - name: c_string
        dataType:
          type: String
      - name: c_float64
        dataType:
          type: Float
      - name: c_bool
        dataType:
          type: String
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - seeds/testSeedSchdRun_Automation_Snowflake_Project_AirflowScheduled.csv
    - seeds/seeds.yml
    createdAt: '2025-04-08 05:30:45'
sqlSources: {}
sqlUnreferencedSources: {}
sqlOrchestratorPipelines: {}
sqlBusinessApps: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: abhisheks+e2etests@prophecy.io
  createdAt: '2025-04-08 05:28:50'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
